/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniGetShm */

#ifndef _Included_jniGetShm
#define _Included_jniGetShm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniGetShm
 * Method:    getShm
 * Signature: (Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray Java_com_stormproject_jniGetShm_getShm
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
